/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExpensesRouteRouteImport } from './routes/_authenticated/expenses/route'
import { Route as AuthenticatedCasinoRouteRouteImport } from './routes/_authenticated/casino/route'
import { Route as AuthenticatedExpensesTotalRouteImport } from './routes/_authenticated/expenses/total'
import { Route as AuthenticatedExpensesListRouteImport } from './routes/_authenticated/expenses/list'
import { Route as AuthenticatedExpensesCreateRouteImport } from './routes/_authenticated/expenses/create'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesRouteRoute =
  AuthenticatedExpensesRouteRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCasinoRouteRoute =
  AuthenticatedCasinoRouteRouteImport.update({
    id: '/casino',
    path: '/casino',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesTotalRoute =
  AuthenticatedExpensesTotalRouteImport.update({
    id: '/total',
    path: '/total',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)
const AuthenticatedExpensesListRoute =
  AuthenticatedExpensesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)
const AuthenticatedExpensesCreateRoute =
  AuthenticatedExpensesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/casino': typeof AuthenticatedCasinoRouteRoute
  '/expenses': typeof AuthenticatedExpensesRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/expenses/create': typeof AuthenticatedExpensesCreateRoute
  '/expenses/list': typeof AuthenticatedExpensesListRoute
  '/expenses/total': typeof AuthenticatedExpensesTotalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/casino': typeof AuthenticatedCasinoRouteRoute
  '/expenses': typeof AuthenticatedExpensesRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/expenses/create': typeof AuthenticatedExpensesCreateRoute
  '/expenses/list': typeof AuthenticatedExpensesListRoute
  '/expenses/total': typeof AuthenticatedExpensesTotalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/casino': typeof AuthenticatedCasinoRouteRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/expenses/create': typeof AuthenticatedExpensesCreateRoute
  '/_authenticated/expenses/list': typeof AuthenticatedExpensesListRoute
  '/_authenticated/expenses/total': typeof AuthenticatedExpensesTotalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/casino'
    | '/expenses'
    | '/profile'
    | '/expenses/create'
    | '/expenses/list'
    | '/expenses/total'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/casino'
    | '/expenses'
    | '/profile'
    | '/expenses/create'
    | '/expenses/list'
    | '/expenses/total'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/casino'
    | '/_authenticated/expenses'
    | '/_authenticated/profile'
    | '/_authenticated/expenses/create'
    | '/_authenticated/expenses/list'
    | '/_authenticated/expenses/total'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casino': {
      id: '/_authenticated/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof AuthenticatedCasinoRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/total': {
      id: '/_authenticated/expenses/total'
      path: '/total'
      fullPath: '/expenses/total'
      preLoaderRoute: typeof AuthenticatedExpensesTotalRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
    '/_authenticated/expenses/list': {
      id: '/_authenticated/expenses/list'
      path: '/list'
      fullPath: '/expenses/list'
      preLoaderRoute: typeof AuthenticatedExpensesListRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
    '/_authenticated/expenses/create': {
      id: '/_authenticated/expenses/create'
      path: '/create'
      fullPath: '/expenses/create'
      preLoaderRoute: typeof AuthenticatedExpensesCreateRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
  }
}

interface AuthenticatedExpensesRouteRouteChildren {
  AuthenticatedExpensesCreateRoute: typeof AuthenticatedExpensesCreateRoute
  AuthenticatedExpensesListRoute: typeof AuthenticatedExpensesListRoute
  AuthenticatedExpensesTotalRoute: typeof AuthenticatedExpensesTotalRoute
}

const AuthenticatedExpensesRouteRouteChildren: AuthenticatedExpensesRouteRouteChildren =
  {
    AuthenticatedExpensesCreateRoute: AuthenticatedExpensesCreateRoute,
    AuthenticatedExpensesListRoute: AuthenticatedExpensesListRoute,
    AuthenticatedExpensesTotalRoute: AuthenticatedExpensesTotalRoute,
  }

const AuthenticatedExpensesRouteRouteWithChildren =
  AuthenticatedExpensesRouteRoute._addFileChildren(
    AuthenticatedExpensesRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCasinoRouteRoute: typeof AuthenticatedCasinoRouteRoute
  AuthenticatedExpensesRouteRoute: typeof AuthenticatedExpensesRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCasinoRouteRoute: AuthenticatedCasinoRouteRoute,
  AuthenticatedExpensesRouteRoute: AuthenticatedExpensesRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
