/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExpensesExpensesRouteImport } from './routes/_authenticated/expenses/_expenses'
import { Route as AuthenticatedExpensesExpensesTotalRouteImport } from './routes/_authenticated/expenses/_expenses/total'
import { Route as AuthenticatedExpensesExpensesListRouteImport } from './routes/_authenticated/expenses/_expenses/list'
import { Route as AuthenticatedExpensesExpensesCreateRouteImport } from './routes/_authenticated/expenses/_expenses/create'

const AuthenticatedExpensesRouteImport = createFileRoute(
  '/_authenticated/expenses',
)()

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpensesExpensesRoute =
  AuthenticatedExpensesExpensesRouteImport.update({
    id: '/_expenses',
    getParentRoute: () => AuthenticatedExpensesRoute,
  } as any)
const AuthenticatedExpensesExpensesTotalRoute =
  AuthenticatedExpensesExpensesTotalRouteImport.update({
    id: '/total',
    path: '/total',
    getParentRoute: () => AuthenticatedExpensesExpensesRoute,
  } as any)
const AuthenticatedExpensesExpensesListRoute =
  AuthenticatedExpensesExpensesListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedExpensesExpensesRoute,
  } as any)
const AuthenticatedExpensesExpensesCreateRoute =
  AuthenticatedExpensesExpensesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedExpensesExpensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/expenses': typeof AuthenticatedExpensesExpensesRouteWithChildren
  '/expenses/create': typeof AuthenticatedExpensesExpensesCreateRoute
  '/expenses/list': typeof AuthenticatedExpensesExpensesListRoute
  '/expenses/total': typeof AuthenticatedExpensesExpensesTotalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/expenses': typeof AuthenticatedExpensesExpensesRouteWithChildren
  '/expenses/create': typeof AuthenticatedExpensesExpensesCreateRoute
  '/expenses/list': typeof AuthenticatedExpensesExpensesListRoute
  '/expenses/total': typeof AuthenticatedExpensesExpensesTotalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteWithChildren
  '/_authenticated/expenses/_expenses': typeof AuthenticatedExpensesExpensesRouteWithChildren
  '/_authenticated/expenses/_expenses/create': typeof AuthenticatedExpensesExpensesCreateRoute
  '/_authenticated/expenses/_expenses/list': typeof AuthenticatedExpensesExpensesListRoute
  '/_authenticated/expenses/_expenses/total': typeof AuthenticatedExpensesExpensesTotalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/expenses'
    | '/expenses/create'
    | '/expenses/list'
    | '/expenses/total'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/profile'
    | '/expenses'
    | '/expenses/create'
    | '/expenses/list'
    | '/expenses/total'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/register'
    | '/_authenticated/profile'
    | '/_authenticated/expenses'
    | '/_authenticated/expenses/_expenses'
    | '/_authenticated/expenses/_expenses/create'
    | '/_authenticated/expenses/_expenses/list'
    | '/_authenticated/expenses/_expenses/total'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses/_expenses': {
      id: '/_authenticated/expenses/_expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesExpensesRouteImport
      parentRoute: typeof AuthenticatedExpensesRoute
    }
    '/_authenticated/expenses/_expenses/total': {
      id: '/_authenticated/expenses/_expenses/total'
      path: '/total'
      fullPath: '/expenses/total'
      preLoaderRoute: typeof AuthenticatedExpensesExpensesTotalRouteImport
      parentRoute: typeof AuthenticatedExpensesExpensesRoute
    }
    '/_authenticated/expenses/_expenses/list': {
      id: '/_authenticated/expenses/_expenses/list'
      path: '/list'
      fullPath: '/expenses/list'
      preLoaderRoute: typeof AuthenticatedExpensesExpensesListRouteImport
      parentRoute: typeof AuthenticatedExpensesExpensesRoute
    }
    '/_authenticated/expenses/_expenses/create': {
      id: '/_authenticated/expenses/_expenses/create'
      path: '/create'
      fullPath: '/expenses/create'
      preLoaderRoute: typeof AuthenticatedExpensesExpensesCreateRouteImport
      parentRoute: typeof AuthenticatedExpensesExpensesRoute
    }
  }
}

interface AuthenticatedExpensesExpensesRouteChildren {
  AuthenticatedExpensesExpensesCreateRoute: typeof AuthenticatedExpensesExpensesCreateRoute
  AuthenticatedExpensesExpensesListRoute: typeof AuthenticatedExpensesExpensesListRoute
  AuthenticatedExpensesExpensesTotalRoute: typeof AuthenticatedExpensesExpensesTotalRoute
}

const AuthenticatedExpensesExpensesRouteChildren: AuthenticatedExpensesExpensesRouteChildren =
  {
    AuthenticatedExpensesExpensesCreateRoute:
      AuthenticatedExpensesExpensesCreateRoute,
    AuthenticatedExpensesExpensesListRoute:
      AuthenticatedExpensesExpensesListRoute,
    AuthenticatedExpensesExpensesTotalRoute:
      AuthenticatedExpensesExpensesTotalRoute,
  }

const AuthenticatedExpensesExpensesRouteWithChildren =
  AuthenticatedExpensesExpensesRoute._addFileChildren(
    AuthenticatedExpensesExpensesRouteChildren,
  )

interface AuthenticatedExpensesRouteChildren {
  AuthenticatedExpensesExpensesRoute: typeof AuthenticatedExpensesExpensesRouteWithChildren
}

const AuthenticatedExpensesRouteChildren: AuthenticatedExpensesRouteChildren = {
  AuthenticatedExpensesExpensesRoute:
    AuthenticatedExpensesExpensesRouteWithChildren,
}

const AuthenticatedExpensesRouteWithChildren =
  AuthenticatedExpensesRoute._addFileChildren(
    AuthenticatedExpensesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
