/* ============================================================================
   Blackjack – Card Engine
   Pure functions for card evaluation, deck building, and shuffling.
   No side effects, no I/O — safe to use on both server and client.
   ============================================================================ */

import * as crypto from "crypto";
import type { Card, Rank, Suit } from "./types";
import { SUITS, RANKS, DECK_COUNT } from "./types";

/* ============================================================================
   Card Value Helpers
   ============================================================================ */

const FACE_CARDS: ReadonlySet<string> = new Set(["J", "Q", "K"]);

/** Numeric value of a single card rank (Ace = 11 initially) */
export function cardValue(rank: Rank): number {
  if (rank === "A") return 11;
  if (FACE_CARDS.has(rank)) return 10;
  return parseInt(rank, 10);
}

/** Best hand total, counting aces as 1 when needed to stay ≤ 21 */
export function handTotal(cards: readonly Card[]): number {
  let total = 0;
  let aces = 0;

  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    if (card.hidden) continue;
    total += cardValue(card.rank);
    if (card.rank === "A") aces++;
  }

  while (total > 21 && aces > 0) {
    total -= 10;
    aces--;
  }

  return total;
}

/** Whether the hand is "soft" (contains an Ace counted as 11) */
export function isSoftHand(cards: readonly Card[]): boolean {
  let total = 0;
  let aces = 0;

  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    if (card.hidden) continue;
    total += cardValue(card.rank);
    if (card.rank === "A") aces++;
  }

  return aces > 0 && total <= 21 && total - 10 >= 1;
}

/** Natural blackjack: exactly 2 visible cards, one Ace + one 10-value */
export function isBlackjack(cards: readonly Card[]): boolean {
  let visibleCount = 0;
  let hasAce = false;
  let hasTen = false;

  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    if (card.hidden) continue;
    visibleCount++;
    if (card.rank === "A") hasAce = true;
    if (FACE_CARDS.has(card.rank) || card.rank === "10") hasTen = true;
  }

  return visibleCount === 2 && hasAce && hasTen;
}

/** Whether the hand can be split (exactly 2 cards of equal value) */
export function canSplit(cards: readonly Card[]): boolean {
  return (
    cards.length === 2 && cardValue(cards[0].rank) === cardValue(cards[1].rank)
  );
}

/* ============================================================================
   Deck & Shoe Building
   ============================================================================ */

/** Build a single 52-card deck */
export function buildDeck(): Card[] {
  const deck: Card[] = new Array<Card>(SUITS.length * RANKS.length);
  let idx = 0;
  for (let s = 0; s < SUITS.length; s++) {
    const suit: Suit = SUITS[s];
    for (let r = 0; r < RANKS.length; r++) {
      deck[idx++] = { suit, rank: RANKS[r] };
    }
  }
  return deck;
}

/** Build a multi-deck shoe (default: 6 decks = 312 cards) */
export function buildShoe(deckCount: number = DECK_COUNT): Card[] {
  const singleDeck = buildDeck();
  const shoe: Card[] = new Array<Card>(singleDeck.length * deckCount);
  for (let d = 0; d < deckCount; d++) {
    const offset = d * singleDeck.length;
    for (let i = 0; i < singleDeck.length; i++) {
      shoe[offset + i] = singleDeck[i];
    }
  }
  return shoe;
}

/**
 * Cryptographically seeded Fisher-Yates shuffle.
 * Uses HMAC-SHA256 derived bytes for high-quality randomness.
 * Mutates and returns the input array for efficiency.
 */
export function shuffleShoe(shoe: Card[], seedHex: string): Card[] {
  const keyBuf = Buffer.from(seedHex, "hex");
  let counter = 0;

  // Pre-calculate how many random bytes we need: 4 per swap
  const totalBytesNeeded = (shoe.length - 1) * 4;
  // Generate all random bytes up front in larger chunks for efficiency
  const allBytes = Buffer.alloc(totalBytesNeeded);
  let allBytesOffset = 0;

  while (allBytesOffset < totalBytesNeeded) {
    const hmac = crypto.createHmac("sha256", keyBuf);
    hmac.update(Buffer.from(counter.toString()));
    const digest = hmac.digest();
    const copyLen = Math.min(digest.length, totalBytesNeeded - allBytesOffset);
    digest.copy(allBytes, allBytesOffset, 0, copyLen);
    allBytesOffset += copyLen;
    counter++;
  }

  // Fisher-Yates using pre-generated bytes
  let byteIdx = 0;
  for (let i = shoe.length - 1; i > 0; i--) {
    const b0 = allBytes[byteIdx];
    const b1 = allBytes[byteIdx + 1];
    const b2 = allBytes[byteIdx + 2];
    const b3 = allBytes[byteIdx + 3];
    byteIdx += 4;

    const rand = ((b0 << 24) >>> 0) + (b1 << 16) + (b2 << 8) + b3;
    const j = rand % (i + 1);

    // Swap
    const tmp = shoe[i];
    shoe[i] = shoe[j];
    shoe[j] = tmp;
  }

  return shoe;
}

/** Reveal all hidden cards in-place (mutates) */
export function revealAllCards(cards: Card[]): Card[] {
  for (let i = 0; i < cards.length; i++) {
    if (cards[i].hidden) {
      cards[i] = { ...cards[i], hidden: false };
    }
  }
  return cards;
}
